/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.charts;

import bestdeal.esprit.controllers.DealNoteControllers;
import bestdeal.esprit.dao.EvaluationDAO;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RectangleAnchor;

/**
 *
 * @author user
 */
public class statistiques extends javax.swing.JFrame {

    /**
     * Creates new form statistiques
     */
    public statistiques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statistiqueTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        statistiqueTable.setModel(new DealNoteControllers());
        jScrollPane1.setViewportView(statistiqueTable);

        jButton1.setText("Générer Statistiques");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-338)/2, 646, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
           int size =statistiqueTable.getRowCount();
           List<Double> notes= new ArrayList<Double>();
           List<Integer> ids = new ArrayList<Integer>();
           EvaluationDAO evaluationsDAO = new  EvaluationDAO();
           
           int idDeal;
           float ess ;
           for(int i=0;i<size;i++)
           {
           
              
               
              
             String d = statistiqueTable.getValueAt(i, 2)+"";
              int id = Integer.parseInt(d);
              
              System.out.println(id);
              ess=evaluationsDAO.getMoyenneMembre(id);
              System.out.println(ess);
              
              notes.add((new Double(ess)));
              ids.add(id);
           
           
           }
              
           
           DefaultCategoryDataset dataset = new DefaultCategoryDataset();
           for(int i=0;i<size;i++)
           {
           
           dataset.setValue(new Double(notes.get(i)), "notes", new Double(ids.get(i)));
           
           
           }
             
           
           
           
           JFreeChart chart = ChartFactory.createBarChart3D("Les deals les plus notés", "Id Deals", "Notes", dataset, PlotOrientation.VERTICAL, true, true, false);
               CategoryPlot p= chart.getCategoryPlot();
               p.setRangeGridlinePaint(Color.black);
               ChartFrame frame = new ChartFrame(" les notes des membres", chart);
               frame.setVisible(true);
               frame.setSize(450,350);
              ValueMarker marker = new ValueMarker(15);
              marker.setLabel("Note evaluations");
               marker.setLabelAnchor(RectangleAnchor.CENTER);
               marker.setPaint(Color.BLACK);
               p.addRangeMarker(marker);
               p.setRangeGridlinePaint(Color.RED);
               
               
               
               
               try{
               
               
               
               
               }
               
               catch(Exception e)
               {}
           
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statistiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statistiques().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable statistiqueTable;
    // End of variables declaration//GEN-END:variables
}
