/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.controllers.CommentaireClientControllers;
import bestdeal.esprit.controllers.CommentaireClientControllers;
import bestdeal.esprit.dao.CommentaireDAO;
import bestdeal.esprit.dao.DealDAO;
import bestdeal.esprit.entities.Commentaire;
import bestdeal.esprit.entities.Deal;
import bestdeal.esprit.entities.Membre;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class addCommentaire extends javax.swing.JFrame {

    /**
     * Creates new form addCommentaire
     */
    public addCommentaire() {
                try {
            SyntheticaLookAndFeel.setWindowsDecorated(false);

        UIManager.put("Synthetica.dialog.icon.enabled", true);
      
        //Application du look SynthLookAndFeel
        //UIManager.setLookAndFeel(new SynthLookAndFeel());
     
        //Application du look MotifLookAndFeel
        //UIManager.setLookAndFeel(new MotifLookAndFeel());
     
        //Application du look SyntheticaBlackEyeLookAndFeel   
      UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
     
        //Application du look SyntheticaStandardLookAndFeel
   // UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
    
   
     //Pour ajouter un nouveau look il faut importer le jar correspondant
     //Voici des liens utiles :
     //http://www.jyloo.com/
             initComponents();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(addCommentaire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(addCommentaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldcomm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Commenter :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 140, 20);

        jTextFieldcomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcommActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcomm);
        jTextFieldcomm.setBounds(200, 80, 320, 30);

        jTable2.setModel(new CommentaireClientControllers());
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 210, 550, 110);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 610, 430);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-618)/2, (screenSize.height-461)/2, 618, 461);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldcommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcommActionPerformed
        // TODO add your handling code here:
        Commentaire comm = new Commentaire();
        comm.setCommentaire(jTextFieldcomm.getText());
//        CommentaireDAO commentaireDAO = new CommentaireDAO();
//        Membre membre = new Membre();
//        Deal deal = new Deal();
//        deal.setIdDeal(2);
//        membre.setIdMembre(2);
//        comm.setDateSys("10/10/2013");
//        comm.setMembre(membre);
//        comm.setDeal(deal);
//        commentaireDAO.create(comm);

        jTable2.setModel(new CommentaireClientControllers());
       jTextFieldcomm.setText(null);
    }//GEN-LAST:event_jTextFieldcommActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCommentaire().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldcomm;
    // End of variables declaration//GEN-END:variables
}
