/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.dao.DealDAO;
import bestdeal.esprit.dao.StockDAO;
import bestdeal.esprit.entities.Deal;
import bestdeal.esprit.entities.Fournisseur;
import bestdeal.esprit.entities.Stock;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
/**
 *
 * @author Oussama
 */
public class AjoutDeal extends javax.swing.JFrame {
public static int xxx;

    public static int getXxx() {
        return xxx;
    }

    public static void setXxx(int xxx) {
        AjoutDeal.xxx = xxx;
    }
    /**
     * Creates new form AjoutDeal
     */
    private String imagePath;
    public AjoutDeal() {
        initComponents();
        jFImageChooser.setVisible(false);
        
        this.setBounds(300, 300, 650, 550);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFImageChooser = new javax.swing.JFrame();
        jFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDate2 = new com.toedter.calendar.JDateChooser();
        jDate1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextDeal = new javax.swing.JTextField();
        jTextville = new javax.swing.JTextField();
        jTextPrix = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonreset = new javax.swing.JButton();
        jButton_ajout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextdetail = new javax.swing.JTextField();
        jTextpourcentage = new javax.swing.JTextField();

        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });
        jFImageChooser.getContentPane().add(jFileChooser, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Catégorie:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Ajouter Deal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 140, 40));

        jLabel4.setText("Deal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, -1));

        jLabel5.setText("Date Début:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 90, -1));

        jLabel6.setText("Date fin:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 70, 20));

        jLabel7.setText("Ville:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 40, -1));

        jLabel8.setText("Description:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, -1));

        jLabel9.setText("Prix:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 360, 50, -1));
        getContentPane().add(jDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 140, -1));
        getContentPane().add(jDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 110, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, 90));
        getContentPane().add(jTextDeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));
        getContentPane().add(jTextville, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, -1));
        getContentPane().add(jTextPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 90, -1));

        jLabel11.setText("Quantité:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 100, -1));

        jButtonreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/quitter.png"))); // NOI18N
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 70, 50));

        jButton_ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/ajout.png"))); // NOI18N
        jButton_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ajoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 70, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/ajout_tof.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 70, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sport", "Informatique", "santé", "cosmitique" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 160, 60));

        jLabel12.setText("Pourcentage :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel13.setText("Details :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel14.setText("Fournisseur :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));
        getContentPane().add(jTextdetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 150, -1));

        jTextpourcentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextpourcentageActionPerformed(evt);
            }
        });
        getContentPane().add(jTextpourcentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajoutActionPerformed
        // TODO add your handling code here:
    
        DealDAO da = new DealDAO();
        Deal d = new Deal();
        
        String mx= null;
        if (jComboBox1.getSelectedIndex()==0){
            mx="sport";
        }
         if (jComboBox1.getSelectedIndex()==1){
            mx="Informatique";
        }
          if (jComboBox1.getSelectedIndex()==2){
            mx="santé";
        }
           if (jComboBox1.getSelectedIndex()==3){
            mx="cosmitique";
        }
           
           int nn=0;
        if (jComboBox2.getSelectedIndex()==0){
            nn=1;
        }
         if (jComboBox2.getSelectedIndex()==1){
            nn=2;
        }
          if (jComboBox2.getSelectedIndex()==2){
            nn=3;
        }
           if (jComboBox2.getSelectedIndex()==3){
            nn=4;
        }
            if (jComboBox2.getSelectedIndex()==4){
            nn=5;
        }
             if (jComboBox2.getSelectedIndex()==5){
            nn=6;
        }
              if (jComboBox2.getSelectedIndex()==6){
            nn=7;
        }
          
         
           
      String nom = jTextDeal.getText();
       String description = jTextArea1.getText();
       String ville = jTextville.getText();     
        float prix = Float.parseFloat(jTextPrix.getText());
        int pr=Integer.parseInt(jTextpourcentage.getText());
        String det=jTextdetail.getText();
        
        
       d.setPrix(prix);
       
d.setCategorie(mx);
       
     d.setNomDeal(nom);
     d.setDescription(description);
     d.setVille(ville);
   Fournisseur f=new Fournisseur(); 
   f.setIdFournisseur(nn);
   StockDAO sDao=new StockDAO();
   Stock sss=new Stock();
   
   
   
   
   int qte=Integer.parseInt(jSpinner1.getValue().toString());
   
   sss.setQteStockDisponible(qte);
   sss.setQteStockInitial(qte);
   
  
        
        Date  dateDebutDeal= jDate1.getDate();
     d.setDateDebutDeal(dateDebutDeal);
     d.setDateFinDeal(jDate2.getDate());
     d.setImage(jLabel10.getText());
     d.setPourcentage(pr);
     d.setDetails(det);
     d.setIdFournisseur(f);
     
      int id = da.create2(d);
      sDao.create2(sss, id);
    }//GEN-LAST:event_jButton_ajoutActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         InterfaceMembre interfacemembre = new InterfaceMembre();
         interfacemembre.setVisible(true);
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFileChooser fc =new JFileChooser(); 
        fc.showOpenDialog(this);
            File file=fc.getSelectedFile();
            if (file !=null)
  {
       jLabel10.setText(file.getPath());         
  }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        // TODO add your handling code here:
        System.out.println(jFileChooser.getSelectedFile().getPath());
        jFImageChooser.setVisible(false);
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextpourcentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextpourcentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextpourcentageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AjoutDeal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_ajout;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDate1;
    private com.toedter.calendar.JDateChooser jDate2;
    private javax.swing.JFrame jFImageChooser;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextDeal;
    private javax.swing.JTextField jTextPrix;
    private javax.swing.JTextField jTextdetail;
    private javax.swing.JTextField jTextpourcentage;
    private javax.swing.JTextField jTextville;
    // End of variables declaration//GEN-END:variables
}
