/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.dao.AdministrateurDAO;
import bestdeal.esprit.dao.MembreDAO;
import bestdeal.esprit.entities.Membre;
import bestdeal.esprit.facebook.ConnexionFacebook;
import javax.swing.JButton;
import javax.swing.JOptionPane;




/**
 *
 * @author Fahmi
 */
public class AuthentificationMembre extends javax.swing.JFrame {
 
    private static int idmembreint;
     private static String  nomloginmembre;
    public static int getIdmembreint() {
        return idmembreint;
    }

    public static void setIdmembreint(int idmembreint) {
        AuthentificationMembre.idmembreint = idmembreint;
    }

    public static String getNomloginmembre() {
        return nomloginmembre;
    }

    public static void setNomloginmembre(String nomloginmembre) {
        AuthentificationMembre.nomloginmembre = nomloginmembre;
    }
    /**
     * Creates new form AuthentificationMembre
     */
    public AuthentificationMembre() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 180, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/seconnecter_2.gif"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 280, 60));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/ffff_2.gif"))); // NOI18N
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 310, 60));

        jLabel4.setForeground(new java.awt.Color(0, 0, 240));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 90, 30));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 180, 30));

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(null);
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.setOpaque(false);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 190, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/User-Accounts_1.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/go-locker_1.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/abstract_color_background_picture_8016-wide.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 650));

        jMenu1.setText("Fichier");

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aide");

        jMenuItem1.setText("A propos de BestDeal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1042)/2, (screenSize.height-696)/2, 1042, 696);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        
        
        MembreDAO membre = new MembreDAO(); 
          boolean trouve = false;
          /*
          for(Membre m:membre.findAll()){
              System.out.println(m);
          }
       */
       if (jTextField1.getText().trim().isEmpty()&& jPasswordField1.getText().trim().isEmpty())
       {
           JOptionPane.showMessageDialog(null, "Aucun champ rempli !!!!!");
       }
       else{
                if(jTextField1.getText().trim().isEmpty()|| jPasswordField1.getText().trim().isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "champ Login ou Mot de passe est vide !!!!");
                }
                else
           
          {    
       for (int i = 0; i < membre.findAll().size()&& (trouve == false); i++)
       { 
           System.out.println(membre.findAll().get(i).getLoginMembre() );
           if(membre.findAll().get(i).getLoginMembre().equals(jTextField1.getText()) && membre.findAll().get(i).getPwdMembre().equals(jPasswordField1.getText())) { 
               
               trouve = true;
               Membre mid=new Membre();
             
                      
                  
              
              
        } else
           { 
              trouve = false;
           } }
       if(trouve == true){
                    
               JOptionPane.showMessageDialog(this, "Bienvenue "+jTextField1.getText());
                setNomloginmembre(jTextField1.getText());  
                Membre m = membre.findByNomType(jTextField1.getText().toString());
                idmembreint=membre.findByIdd(nomloginmembre).getIdMembre();
                 System.out.println("id : "+idmembreint);
                System.out.println("type : "+m.getType());
                
                if(m.getType().equals( "Membre"))
                {
               InterfaceMembre me=new InterfaceMembre();
               this.setVisible(false);
               me.setVisible(true);
                }
                else {
                    
                    if(m.getType().equals( "Vendeur"))
                   
                {
                    InterfaceVendeur mv=new InterfaceVendeur();
               this.setVisible(false);
               mv.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Vous n'etes pas un membre "+jTextField1.getText());
                }}
       }
       else{
           JOptionPane.showMessageDialog(this, "login ou mot de passe invalide !!!!!");
        
       }
       }
       }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ConnexionFacebook connexionFacebook = new ConnexionFacebook();
        connexionFacebook.loginFb();
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        inscriptionMembre i=new inscriptionMembre();
       i.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AuthentificationMembre.this.setVisible(false);

        Accueil a =new Accueil();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Apropos ap=new Apropos();
        ap.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setVisible(false);
        RecuperationMP rec =new RecuperationMP();
        rec.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AuthentificationMembre().setVisible(true);
                
               
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
