/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.controllers.membreController;
import bestdeal.esprit.dao.MembreDAO;
import bestdeal.esprit.entities.Membre;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaLookAndFeel;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class DésactiverCompte extends javax.swing.JFrame {

    /**
     * Creates new form DésactiverCompte
     */
    public DésactiverCompte() {
        try {
            SyntheticaLookAndFeel.setWindowsDecorated(false);

        UIManager.put("Synthetica.dialog.icon.enabled", true);
      
        //Application du look SynthLookAndFeel
        //UIManager.setLookAndFeel(new SynthLookAndFeel());
     
        //Application du look MotifLookAndFeel
      //  UIManager.setLookAndFeel(new MotifLookAndFeel());
     
        //Application du look SyntheticaBlackEyeLookAndFeel   
       UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
     
        //Application du look SyntheticaStandardLookAndFeel
   //  UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
    
   
     //Pour ajouter un nouveau look il faut importer le jar correspondant
     //Voici des liens utiles :
     //http://www.jyloo.com/
             initComponents();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DésactiverCompte.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DésactiverCompte.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledésa = new javax.swing.JTable();
        jButtonDésactiver = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabledésa.setModel(new membreController()

        );
        jScrollPane1.setViewportView(jTabledésa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 860, 133);

        jButtonDésactiver.setText("Désactiver");
        jButtonDésactiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDésactiverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDésactiver);
        jButtonDésactiver.setBounds(300, 253, 83, 23);

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonQuitter);
        jButtonQuitter.setBounds(513, 253, 67, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bkg-7.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 310);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-932)/2, (screenSize.height-351)/2, 932, 351);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed

        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jButtonDésactiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDésactiverActionPerformed
                 
//        int x = jTabledésa.getSelectedRow();
//			System.out.println(x);	
//				//int y = Integer.parseInt(jTabledésa.getValueAt(x,4) + "");
//                                //System.out.println(y);
//				MembreDAO membreDAO = new MembreDAO();
//                                membreDAO.DesactiverMembre(x, 0);
//                                
//                                
//        jTabledésa.setModel(new membreController());
          
          int a = jTabledésa.getSelectedRow();
          int id = ((Integer)jTabledésa.getValueAt(a, 1));
          System.out.println(a);
          MembreDAO membre = new MembreDAO();
          //membre.DesactiverMembre(id);
           JOptionPane.showMessageDialog(this, " Compte Membre désactivé");
    }//GEN-LAST:event_jButtonDésactiverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DésactiverCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DésactiverCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DésactiverCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DésactiverCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DésactiverCompte().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDésactiver;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledésa;
    // End of variables declaration//GEN-END:variables
}
