/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.controllers.ListeFourinisseurControllers;
import bestdeal.esprit.dao.FournisseurDAO;
import bestdeal.esprit.entities.Fournisseur;
import bestdeal.esprit.util.Verification;
import javax.swing.JOptionPane;

/**
 *
 * @author nesrin
 */
public class ListeFournisseur extends javax.swing.JFrame {

    /**
     * Creates new form Fournisseur
     */
    public ListeFournisseur() {
        initComponents();
       jTextField1.setVisible(false);      
       jTextField2.setVisible(false);  
       jTextField3.setVisible(false); 
       jTextField4.setVisible(false); 
       jLabel2.setVisible(false); 
       jLabel3.setVisible(false); 
       jLabel4.setVisible(false); 
       jLabel5.setVisible(false); 
       jLabel6.setVisible(false); 
       jLabel7.setVisible(false); 
       jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new ListeFourinisseurControllers());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 69, 744, 173));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Liste des Fournisseurs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, 160, 26));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/modifier.gif"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 50, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/add.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Modifier Fournisseur");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 283, 160, -1));

        jLabel4.setText("Adresse :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 533, -1, -1));

        jLabel3.setText("Mail :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 426, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 476, 127, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 423, 127, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 363, 127, -1));

        jLabel5.setText("Telephone :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 479, -1, -1));

        jLabel6.setText("Nom Fournisseur :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 366, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 530, 127, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Ajouter Fournisseur");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 283, 160, -1));

        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 597, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/supp.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 50, 50));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-811)/2, (screenSize.height-694)/2, 811, 694);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTextField1.setVisible(true);     
       jTextField2.setVisible(true); 
       jTextField3.setVisible(true); 
       jTextField4.setVisible(true); 
       jLabel2.setVisible(false); 
       jLabel7.setVisible(true); 
       jLabel3.setVisible(true); 
       jLabel4.setVisible(true); 
       jLabel5.setVisible(true); 
       jLabel6.setVisible(true); 
       jButton3.setVisible(true);     
        jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int row = jTable1.getSelectedRow();
if(row == -1){
     JOptionPane.showMessageDialog(this, "veuillez selectionnéz une ligne!!!!");
}else{
        Fournisseur f = new Fournisseur();
       int x =jTable1.getSelectedRow();
       String d = jTable1.getValueAt(x, 0)+"";
       int id = Integer.parseInt(d);
        f.setIdFournisseur(id);
        f.setNomFournisseur(jTextField1.getText());
        f.setMailFournisseur(jTextField2.getText());
        f.setTelFournisseur(jTextField3.getText());
        f.setAdresseFournisseur(jTextField4.getText());

        FournisseurDAO fourdao = new FournisseurDAO();
        fourdao.update(f);
         jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
        JOptionPane.showMessageDialog(this, "Modification effectué avec succés !!!!");
        jTable1.setModel(new ListeFourinisseurControllers());
       jTextField1.setVisible(false);      
       jTextField2.setVisible(false);  
       jTextField3.setVisible(false); 
       jTextField4.setVisible(false); 
       jLabel2.setVisible(false); 
       
       jLabel3.setVisible(false); 
       jLabel4.setVisible(false); 
       jLabel5.setVisible(false); 
       jLabel6.setVisible(false); 
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       jTextField1.setVisible(true);     
       jTextField2.setVisible(true); 
       jTextField3.setVisible(true); 
       jTextField4.setVisible(true); 
       jLabel2.setVisible(true); 
       jLabel3.setVisible(true); 
       jLabel4.setVisible(true); 
       jLabel5.setVisible(true); 
       jLabel6.setVisible(true); 
       jButton3.setVisible(false);
       jLabel7.setVisible(false); 
        int x =jTable1.getSelectedRow();
                    
       String nom = jTable1.getValueAt(x, 1)+"";
       String mail = jTable1.getValueAt(x, 2)+"";
       String tel = jTable1.getValueAt(x, 3)+"";
       String adresse = jTable1.getValueAt(x, 4)+"";
       
      
       
       jTextField1.setText(nom);
       jTextField2.setText(mail);
       jTextField3.setText(tel);
       jTextField4.setText(adresse);
       
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Verification v=new Verification();
        v.verfmail(jTextField2.getText());
        if (  v.verfmail(jTextField2.getText())){
        jButton3.setVisible(true);
        Fournisseur f=new Fournisseur();
        f.setNomFournisseur(jTextField1.getText());
        f.setMailFournisseur(jTextField2.getText());
        f.setTelFournisseur(jTextField3.getText());
        f.setAdresseFournisseur(jTextField4.getText());

        FournisseurDAO fourDAO =new FournisseurDAO();
        fourDAO.create(f);
        JOptionPane.showMessageDialog(this, "Ajout effectué avec succés!");
          jTable1.setModel(new ListeFourinisseurControllers());
         jTextField1.setVisible(false);     
       jTextField2.setVisible(false); 
       jTextField3.setVisible(false); 
       jTextField4.setVisible(false);
        jLabel7.setVisible(false); 
       jLabel3.setVisible(false); 
       jLabel4.setVisible(false); 
       jLabel5.setVisible(false); 
       jLabel6.setVisible(false); 
       jButton3.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int row = jTable1.getSelectedRow();
       if(row == -1){
     JOptionPane.showMessageDialog(this, "veuillez selectionnéz une ligne!!!!");
}else{
               Fournisseur f = new Fournisseur();
       int x =jTable1.getSelectedRow();
       String d = jTable1.getValueAt(x, 0)+"";
       int id = Integer.parseInt(d);
      
        FournisseurDAO fourdao = new FournisseurDAO();
        fourdao.delete(id);

        JOptionPane.showMessageDialog(this, "suppression  effectué avec succés !!!!");
        jTable1.setModel(new ListeFourinisseurControllers());
         jTextField1.setVisible(false);      
       jTextField2.setVisible(false);  
       jTextField3.setVisible(false); 
       jTextField4.setVisible(false); 
       jLabel2.setVisible(false); 
       
       jLabel3.setVisible(false); 
       jLabel4.setVisible(false); 
       jLabel5.setVisible(false); 
       jLabel6.setVisible(false); 
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeFournisseur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
