/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.controllers.ListeDealControllers;
import bestdeal.esprit.controllers.ListeDealControllersRecherche;
import bestdeal.esprit.dao.DealDAO;
import bestdeal.esprit.entities.Deal;
import bestdeal.esprit.map.GMaps;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author nesrin
 */
public class ListeDeal extends javax.swing.JFrame {

    /**
     * @return the cat
     */
    public static String getCat() {
        return cat;
    }

    /**
     * @param aCat the cat to set
     */
    public static void setCat(String aCat) {
        cat = aCat;
    }

    /**
     * @return the ndeal
     */
    public static String getNdeal() {
        return ndeal;
    }

    /**
     * @param aNdeal the ndeal to set
     */
    public static void setNdeal(String aNdeal) {
        ndeal = aNdeal;
    }

    /**
     * @return the nville
     */
    public static String getNville() {
        return nville;
    }

    /**
     * @param aNville the nville to set
     */
    public static void setNville(String aNville) {
        nville = aNville;
    }

    /**
     * @return the prixxx
     */
    public static float getPrixxx() {
        return prixxx;
    }

    /**
     * @param aPrixxx the prixxx to set
     */
    public static void setPrixxx(float aPrixxx) {
        prixxx = aPrixxx;
    }

    /**
     * @return the iddealll
     */
    public static int getIddealll() {
        return iddealll;
    }

    /**
     * @param aIddealll the iddealll to set
     */
    public static void setIddealll(int aIddealll) {
        iddealll = aIddealll;
    }

    
    GMaps map = new GMaps(500, 500);
    
    public ArrayList<String> ma = new ArrayList<String>();
    
    private static String cat;
    private static String ndeal;
    private static String nville;
    private static float prixxx;
    private static int iddealll;
    
    public ListeDeal() {
        initComponents();
        ma.add("Bizerte");
        try {
            jLabel1.setText(map.setMap(map.arrList.get(0), "Tunisia", 500, 500));
        } catch (Exception ex) {
            Logger.getLogger(ListeDeal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtrecherche = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new ListeDealControllers());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 690, 160));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/rech.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 58, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/delete.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 56, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/modify.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 50, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 430, 270));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButton5.setText("Rechercher deal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));
        getContentPane().add(txtrecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 110, -1));

        jButton6.setText("Retour");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-742)/2, (screenSize.height-518)/2, 742, 518);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int row=jTable1.getSelectedRow();
       int id=(int)jTable1.getModel().getValueAt(row,0);
       DealDAO dealDao=new DealDAO();
       dealDao.delete(id);
       jTable1.setModel(new ListeDealControllers());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        DetailDeal det=new DetailDeal();
        det.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            map.arrList.add(jTextField1.getText().toString());
            map.arrList.add(jTextField2.getText().toString());

 try {
            jLabel1.setText(map.setMap(map.arrList.get(0), "Tunisia", 500, 500));
        } catch (Exception ex) {
            Logger.getLogger(ListeDeal.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
    }//GEN-LAST:event_formMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      int row=jTable1.getSelectedRow();
       int id=(int)jTable1.getModel().getValueAt(row,0);
       DealDAO dealDao=new DealDAO();
       Deal d=new Deal();
       if (row==-1){
           System.out.println("pas de ligne selectioné");
       }else {
           setIddealll((int)jTable1.getModel().getValueAt(row,0));
           setNdeal(jTable1.getModel().getValueAt(row,1).toString());
           setCat(jTable1.getModel().getValueAt(row,2).toString());
           setNville(jTable1.getModel().getValueAt(row,3).toString());
           setPrixxx((float)jTable1.getModel().getValueAt(row,4));
           
           System.out.println(jTable1.getModel().getValueAt(row,2).toString());
           this.setVisible(false);
           ModifierDeal mod=new ModifierDeal();
           mod.show();
           
           
       }
           
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int row=jTable1.getSelectedRow();
       int id=(int)jTable1.getModel().getValueAt(row,0);
       DealDAO dealDao=new DealDAO();
       dealDao.delete(id);
       jTable1.setModel(new ListeDealControllers());
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       DealDAO dDAO=new DealDAO();
       
       
       if(txtrecherche.getText().isEmpty())
       {
           jTable1.setModel(new ListeDealControllers());
       }
       else 
       {
            jTable1.setModel(new ListeDealControllersRecherche(txtrecherche.getText()));
       }
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.hide();
        new InterfaceMembre().show();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ListeDeal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtrecherche;
    // End of variables declaration//GEN-END:variables
}
