/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import bestdeal.esprit.controllers.CommentaireClientControllers;
import bestdeal.esprit.dao.CommentaireDAO;

import bestdeal.esprit.dao.DealDAO;
import bestdeal.esprit.dao.EvaluationDAO;
import bestdeal.esprit.dao.FournisseurDAO;
import bestdeal.esprit.entities.Commentaire;
import bestdeal.esprit.entities.Deal;
import bestdeal.esprit.entities.Evaluation;
import bestdeal.esprit.entities.Fournisseur;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import bestdeal.esprit.map.StaticMaps;
import java.awt.Dimension;
import java.awt.Image;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
/**
 *
 * @author Fahmi
 */
public class NewJFrame1 extends javax.swing.JFrame {
int id;
DealDAO DDAO = new DealDAO();
FournisseurDAO FDAO = new FournisseurDAO();
Fournisseur f = new Fournisseur();
ListesDeals d = new ListesDeals();
CommentaireDAO cmdDAO =new CommentaireDAO();
Commentaire c =new Commentaire();
Deal deal = new Deal();
private StaticMaps ObjStaticMaps=new StaticMaps();
private String n;
private int note;
    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        imagePanel1.setImage(new ImageIcon(this.getClass().getResource("slider-background-4.jpg")).getImage());
        n=AuthentificationMembre.getNomloginmembre();
         jTable2.setVisible(false);
        id=d.getId(); 
        jlabelNomCompte.setText(n);
        deal  = DDAO.findByIddd(id);
        jLabel2.setText(deal.getDescription());
        jLabel3.setText(deal.getImage());
        jLabel6.setText(deal.getDetails());
        jLabel10.setText(String.valueOf(deal.getPrix()));
        jLabel11.setText(String.valueOf((((deal.getPrix())*(deal.getPourcentage())/100))));
        jLabel1.setText((String.valueOf((deal.getPrix())-((deal.getPrix())*(deal.getPourcentage())/100))));
       
        f= FDAO.findById(deal.getIdFournisseur().getIdFournisseur());
        System.out.println(f);
       
        
        jLabel9.setText(f.getAdresseFournisseur());
        jLabel16.setText(f.getNomFournisseur());
        jLabel17.setText(f.getTelFournisseur());
        jLabel7.setText(String.valueOf(deal.getPourcentage()));
        try {
           
            this.creerMap(deal.getVille());
        } catch (MalformedURLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
        jetoile1.setVisible(false);
        jetoile2.setVisible(false);
        jetoile3.setVisible(false);
        jetoile4.setVisible(false);
        jetoile5.setVisible(false);
    }
    private void creerMap(String ch) throws MalformedURLException, UnsupportedEncodingException{
        jSlider1.setVisible(true);
         if(!ch.isEmpty()){
             
             Image imageMap=ObjStaticMaps.getStaticMap(ch,
                     Integer.valueOf(jSlider1.getValue()),new Dimension(240,240),
                     10,this.SelectionerFormat(),
                     this.SelectionnerTypeMap());
            if(imageMap!=null){
                ImageIcon imgIcon=new ImageIcon(imageMap);
                Icon iconImage=(Icon)imgIcon;
                labelmap.setIcon(iconImage);
            }
         }
     }
    private StaticMaps.Maptype SelectionnerTypeMap(){
        StaticMaps.Maptype type= StaticMaps.Maptype.roadmap;
        switch(jCombo_type.getSelectedItem().toString()){
            case "roadmap":
                type= StaticMaps.Maptype.roadmap;
                break;
            case "satellite":
                type= StaticMaps.Maptype.satellite;
                break;
            case "hybrid":
                type= StaticMaps.Maptype.hybrid;
                break;
            case "terrain":
                type= StaticMaps.Maptype.terrain;
                break;
        }
        return type;
    } 
 private StaticMaps.Format SelectionerFormat(){
        StaticMaps.Format format= StaticMaps.Format.jpg;
        return format;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new bestdeal.esprit.util.ImagePanel();
        transparentPanel1 = new bestdeal.esprit.util.TransparentPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jetoile4 = new javax.swing.JLabel();
        jetoile5 = new javax.swing.JLabel();
        jetoile3 = new javax.swing.JLabel();
        jetoile1 = new javax.swing.JLabel();
        jetoile2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jCombo_type = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jlabelNomCompte = new javax.swing.JLabel();
        labelmap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transparentPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("jLabel11");
        transparentPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("jLabel10");
        transparentPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("jLabel1");
        transparentPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("DT");
        transparentPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel3.setText("Image");
        transparentPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel4.setText("jLabel2");
        transparentPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel9.setText("jLabel9");
        transparentPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jLabel16.setText("jLabel16");
        transparentPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        jLabel17.setText("jLabel17");
        transparentPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        transparentPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 20, 30));

        jetoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jetoile4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jetoile4MouseClicked(evt);
            }
        });
        transparentPanel1.add(jetoile4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        jetoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jetoile5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jetoile5MouseClicked(evt);
            }
        });
        transparentPanel1.add(jetoile5, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 540, -1, -1));

        jetoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jetoile3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jetoile3MouseClicked(evt);
            }
        });
        transparentPanel1.add(jetoile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 540, -1, -1));

        jetoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jetoile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jetoile1MouseClicked(evt);
            }
        });
        transparentPanel1.add(jetoile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 535, 40, 50));

        jetoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jetoile2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jetoile2MouseClicked(evt);
            }
        });
        transparentPanel1.add(jetoile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 540, -1, -1));

        jLabel6.setText("jLabel6");
        transparentPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel7.setText("Détails :");
        transparentPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jButton5.setText("note");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        transparentPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        jButton1.setText("Réserver");
        transparentPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        jTable2.setModel(new bestdeal.esprit.controllers.CommentaireClientControllers());
        jTable2.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable2.getColumnModel().getColumn(4).setMinWidth(0);
        jTable2.getColumnModel().getColumn(4).setWidth(0);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        transparentPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 480, 130));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        transparentPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 50, 40));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        transparentPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 50, 38));

        jSlider1.setMaximum(20);
        jSlider1.setMinimum(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setValue(15);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        transparentPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, -1, 180));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(214, 12, 12));
        jLabel8.setText("pourcentage");
        transparentPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 130, 50));

        jCombo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "roadmap", "satellite", "hybrid", "terrain" }));
        transparentPanel1.add(jCombo_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(237, 15, 15));
        jLabel15.setText("%");
        transparentPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        jlabelNomCompte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlabelNomCompte.setForeground(new java.awt.Color(240, 240, 240));
        jlabelNomCompte.setText("fazet");
        transparentPanel1.add(jlabelNomCompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 160, 30));
        transparentPanel1.add(labelmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 438, 240, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/gui/slider-background-4.jpg"))); // NOI18N
        transparentPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addComponent(transparentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addComponent(transparentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        note =  Integer.parseInt(jSpinner1.getValue().toString());
        //t.setText(note+"");
        List listlabel= new ArrayList();
        listlabel.add(jetoile1);
        listlabel.add(jetoile2);
        listlabel.add(jetoile3);
        listlabel.add(jetoile4);
        listlabel.add(jetoile5);
        for(int i=0;i<note;i++)
        {
            if (note ==1) {jetoile1.setVisible(true);}
            if (note ==2) {jetoile2.setVisible(true);}
            if (note ==3) {jetoile3.setVisible(true);}
            if (note ==4) {jetoile4.setVisible(true);}
            if (note ==5) {jetoile5.setVisible(true);}
        }
        for(int j=0;j<=note;j++)
        {

            if (note ==4) {jetoile5.setVisible(false);}
            if (note ==3) {jetoile4.setVisible(false);}
            if (note ==2) {jetoile3.setVisible(false);}
            if (note ==1) {jetoile2.setVisible(false);}
            if (note ==0) {jetoile1.setVisible(false);}

        }
        
        
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jetoile4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jetoile4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jetoile4MouseClicked

    private void jetoile5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jetoile5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jetoile5MouseClicked

    private void jetoile3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jetoile3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jetoile3MouseClicked

    private void jetoile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jetoile1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jetoile1MouseClicked

    private void jetoile2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jetoile2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jetoile2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        EvaluationDAO evaluationDAO = new EvaluationDAO();
        Evaluation ev= new Evaluation();
        int note = Integer.parseInt( jSpinner1.getValue().toString());
        //        ev.setIdDeal(deal);
        //        ev.setIdMembre();
        ev.setNote(note);
        evaluationDAO.create(ev);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTable2.getColumnModel().getColumn(4).setMaxWidth(0);
        jTable2.getColumnModel().getColumn(4).setMinWidth(0);
        jTable2.getColumnModel().getColumn(4).setWidth(0);
        jTable2.setVisible(true);

        jTable2.setModel(new CommentaireClientControllers());
        //  c= cmdDAO.findById(c.getDeal().getIdDeal());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        try {
            this.creerMap(deal.getVille());
        } catch (MalformedURLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bestdeal.esprit.util.ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jCombo_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jetoile1;
    private javax.swing.JLabel jetoile2;
    private javax.swing.JLabel jetoile3;
    private javax.swing.JLabel jetoile4;
    private javax.swing.JLabel jetoile5;
    private javax.swing.JLabel jlabelNomCompte;
    private javax.swing.JLabel labelmap;
    private bestdeal.esprit.util.TransparentPanel transparentPanel1;
    // End of variables declaration//GEN-END:variables

     
 
}
