/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.dao.DealDAO;
import bestdeal.esprit.dao.EvaluationDAO;
import bestdeal.esprit.entities.Deal;
import bestdeal.esprit.entities.Evaluation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Oussama
 */
public class Note_1 extends javax.swing.JFrame {

    private int note;
  
    
    
    /**
     * Creates new form Note
     */
    private Deal deal;
    public Note_1() {
        
        initComponents();
        
        
        this.setBounds(300, 300, 650, 550);
        
        DealDAO dealDAO = new DealDAO();
        List<Deal> dea = dealDAO.findAll();
        for (Deal d : dea) {
        jComboBox1.addItem(d.getNomDeal());}
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel9.setVisible(false);
        jLabel15.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        t = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Deal:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 90, 60, 16);

        jLabel2.setText("Description:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 150, 90, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 150, 166, 96);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Noter DEAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(254, 30, 122, 29);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 90, 160, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 340, 80, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 340, 80, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 340, 80, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(470, 340, 80, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestdeal/esprit/image/starr.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(130, 330, 80, 70);
        getContentPane().add(n);
        n.setBounds(350, 270, 70, 40);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(210, 280, 70, 40);
        getContentPane().add(t);
        t.setBounds(300, 280, 60, 30);

        jButton1.setText("note");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 290, 57, 25);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 650, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel14MouseClicked
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here: 
        DealDAO  dealDAO = new DealDAO();
           Deal d = new Deal();
         d= dealDAO.find_Deal_By_N(jComboBox1.getSelectedItem().toString());
         System.out.println(d);
        jTextArea1.setText(d.getDescription());
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
          note =  Integer.parseInt(jSpinner1.getValue().toString());
          //t.setText(note+"");
          List listlabel= new ArrayList();
           listlabel.add(jLabel15);
          listlabel.add(jLabel9);
          listlabel.add(jLabel12);
          listlabel.add(jLabel13);
          listlabel.add(jLabel4);
          for(int i=0;i<note;i++)
          {
         if (note ==1) {jLabel15.setVisible(true);}
         if (note ==2) {jLabel9.setVisible(true);}
         if (note ==3) {jLabel12.setVisible(true);}
         if (note ==4) {jLabel13.setVisible(true);}
         if (note ==5) {jLabel14.setVisible(true);}
          }
           for(int j=0;j<=note;j++)
          {
      
         if (note ==4) {jLabel14.setVisible(false);}
         if (note ==3) {jLabel13.setVisible(false);}
          if (note ==2) {jLabel12.setVisible(false);}
          if (note ==1) {jLabel9.setVisible(false);}
           if (note ==0) {jLabel15.setVisible(false);}
         
          }
          
          
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
        EvaluationDAO evaluationDAO = new EvaluationDAO();
        Evaluation ev= new Evaluation();
        int note = Integer.parseInt( jSpinner1.getValue().toString());
        ev.setIdDeal(deal);
       // ev.setIdMembre();
        ev.setNote(note);
         evaluationDAO.create(ev);
        
    }//GEN-LAST:event_jButton1ActionPerformed


         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Note_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Note_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Note_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Note_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Note_1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables

    
    }

