/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

/**
 *
 * @author user
 */


import javax.mail.Message;
import javax.mail.Transport;
import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

 
public class Parrainage extends javax.swing.JFrame {

    /**
     * Creates new form Parrainage
     */
    public Parrainage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ToLabel = new javax.swing.JLabel();
        ToText = new javax.swing.JTextField();
        EnvoyerButton = new javax.swing.JButton();
        FromLabel = new javax.swing.JLabel();
        FromText = new javax.swing.JTextField();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Parrainer vos amis !! ");

        ToLabel.setText("L'e-mail de votre ami(e): *");

        EnvoyerButton.setText("Envoyer");
        EnvoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvoyerButtonActionPerformed(evt);
            }
        });

        FromLabel.setText("Votre e-mail:*");

        annulerButton.setText("annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(ToLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(FromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FromText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(ToText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(EnvoyerButton)
                        .addGap(92, 92, 92)
                        .addComponent(annulerButton)))
                .addGap(88, 249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ToText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnvoyerButton)
                    .addComponent(annulerButton))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnvoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvoyerButtonActionPerformed

                       String From = FromText.getText();
                       String To = ToText.getText();
                       
                       Properties pros = new Properties();
                       pros.put("mail.smtp.host", "smtp.gmail.com");
                       pros.put("mail.smtp.socketFactory.port", "465");
                       pros.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                       pros.put("mail.smtp.auth", "true");
                       pros.put("mail.smtp.port", "465");
                       
                       
                       Session session = Session.getDefaultInstance(pros,                           
                               
                               
                               
                               new javax.mail.Authenticator() {
                               
                               
                               
                                   @Override
                               protected PasswordAuthentication getPasswordAuthentication()
                               {
                               
                               return new PasswordAuthentication("bestdeal3a17@gmail.com", "salma_souissi");
                               
                               }
                               
                               
                               
                               
                               }
                               
                               
                               
                               
                               
                               
                               );
                       
                       
                       try {
                       
                            Message message = new MimeMessage(session);
                            message.setFrom(new InternetAddress(From));
                            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(To));
                            message.setSubject("Parrainage");
                            message.setText("Vous recevrez un coupon de 6 dinars si celui ci s'inscrit et profite d'une offre dealoo.tn dans les 72h.");
                            Transport.send(message);
                            
                            
                       JOptionPane.showMessageDialog(null, "Votre message de parrainage a été envoyé avec succès ");
                       
                       
                       
                       
                       }
                       
                       
                       
                       catch(Exception e )
                       {
                           
                       JOptionPane.showMessageDialog(null, "Verifier les emails saisis");
                       
                       }                       
                       
                       
               



    }//GEN-LAST:event_EnvoyerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_annulerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parrainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parrainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parrainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parrainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parrainage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnvoyerButton;
    private javax.swing.JLabel FromLabel;
    private javax.swing.JTextField FromText;
    private javax.swing.JLabel ToLabel;
    private javax.swing.JTextField ToText;
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
