/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bestdeal.esprit.gui;

import bestdeal.esprit.dao.DealDAO;
import bestdeal.esprit.dao.DealProposéDAO;
import bestdeal.esprit.entities.Deal;
import bestdeal.esprit.entities.DealPropose;
import java.text.Normalizer;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ProposerDeal extends javax.swing.JFrame {
private static int idv;

    public static int getIdv() {
        return idv;
    }

    public static void setIdv(int idv) {
        ProposerDeal.idv = idv;
    }
    /**
     * Creates new form ProposerDeal
     */
    public ProposerDeal() {
        initComponents();
        setIdv(AuthentificationMembre.getIdmembreint());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDescription = new javax.swing.JTextArea();
        jTextTitre = new javax.swing.JTextField();
        jTextCategorie = new javax.swing.JTextField();
        jTextVille = new javax.swing.JTextField();
        jTextPrix = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jCalendarDeb = new com.toedter.calendar.JDateChooser();
        jCalendarFin = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Titre du deal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 120, 14);

        jLabel2.setText("Date début");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 130, 120, 14);

        jLabel3.setText("Date fin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 120, 14);

        jLabel4.setText("catégorie");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 120, 14);

        jLabel5.setText("Ville");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 320, 90, 14);

        jLabel6.setText("prix");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 370, 90, 14);

        jTextDescription.setColumns(20);
        jTextDescription.setRows(5);
        jScrollPane1.setViewportView(jTextDescription);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 420, 180, 96);

        jTextTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTitreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTitre);
        jTextTitre.setBounds(187, 70, 160, 30);

        jTextCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCategorieActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCategorie);
        jTextCategorie.setBounds(190, 240, 160, 30);
        getContentPane().add(jTextVille);
        jTextVille.setBounds(190, 300, 150, 30);

        jTextPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrixActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPrix);
        jTextPrix.setBounds(190, 360, 150, 30);

        jLabel7.setText("Description");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 440, 100, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Espace Vendeur");
        jLabel8.setIconTextGap(6);
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 14));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(122, 19, 270, 30);

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAjouter);
        jButtonAjouter.setBounds(280, 590, 100, 23);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnnuler);
        jButtonAnnuler.setBounds(389, 590, 90, 23);
        getContentPane().add(jCalendarDeb);
        jCalendarDeb.setBounds(190, 120, 160, 30);
        getContentPane().add(jCalendarFin);
        jCalendarFin.setBounds(190, 180, 160, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\fichier compressé\\Monkee-Boy Blurred Backgrounds\\bkg-1.jpg")); // NOI18N
        jLabel9.setText(" ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 10, 470, 620);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-501)/2, (screenSize.height-661)/2, 501, 661);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTitreActionPerformed

    private void jTextCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCategorieActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
         dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
    
        DealPropose deal = new DealPropose();
         deal.setNomDeal(jTextTitre.getText());
         deal.setDateDebutDeal(jCalendarDeb.getDate());
           deal.setDateFinDeal(jCalendarFin.getDate());
         deal.setCategorie(jTextCategorie.getText());
         deal.setVille(jTextVille.getText());
         deal.setPrix(Float.parseFloat(jTextPrix.getText()));
         deal.setDescription(jTextDescription.getText());
         deal.setIdMembrev(getIdv());
        DealProposéDAO DealDAO = new DealProposéDAO();
        DealDAO.create(deal);
        
// if (jTextTitre.getText().trim().equals("") && jTextCategorie.getText().trim().equals("") && 
//         jTextVille.getText().trim().equals("") && jTextDescription.getText().trim().equals("") && 
//         jCalendarDeb.getDate().equals("") && jCalendarFin.getDate().equals("") && jTextPrix.getText().trim().equals(""))
//          {
//            JOptionPane.showMessageDialog(this, "Aucun champs n'est rempli");
//
//        }

        jTextTitre.setText("");
         jTextCategorie.setText("");
          jTextVille.setText("");
           jTextDescription.setText("");
           jCalendarDeb.setCalendar(null);
           jCalendarFin.setCalendar(null);
           jTextPrix.setText(null);
           
           
        JOptionPane.showMessageDialog(this, "Bravo!"); 
        this.setVisible(false);
        ConsulterProposition c = new ConsulterProposition();
        c.setVisible(true);

    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jTextPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProposerDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProposerDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProposerDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProposerDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProposerDeal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonAnnuler;
    private com.toedter.calendar.JDateChooser jCalendarDeb;
    private com.toedter.calendar.JDateChooser jCalendarFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCategorie;
    private javax.swing.JTextArea jTextDescription;
    private javax.swing.JTextField jTextPrix;
    private javax.swing.JTextField jTextTitre;
    private javax.swing.JTextField jTextVille;
    // End of variables declaration//GEN-END:variables
}
